# infrastructure/code/github_pre_creator.py

"""
Git-based PR creator with auto-commit support.

Flow:
1. Detect modified/new .py files
2. Ask user for commit message
3. Stage files
4. Commit
5. Create PR via GitHub API
"""

import subprocess
import requests


class GitHubPreCreator:

    def __init__(self, token: str, repo: str, base_branch: str = "main"):
        self.token = token
        self.repo = repo
        self.base_branch = base_branch
        self.base_url = "https://api.github.com"

    # --------------------------------------------------
    # GIT DETECTION
    # --------------------------------------------------

    def _get_py_changes(self):
        """
        Returns modified + untracked .py files.
        """

        modified = subprocess.run(
            ["git", "diff", "--name-only", "HEAD"],
            capture_output=True,
            text=True,
            check=True
        ).stdout.splitlines()

        untracked = subprocess.run(
            ["git", "ls-files", "--others", "--exclude-standard"],
            capture_output=True,
            text=True,
            check=True
        ).stdout.splitlines()

        all_files = modified + untracked

        py_files = [f for f in all_files if f.endswith(".py")]

        return list(set(py_files))

    # --------------------------------------------------

    def _get_current_branch(self):
        return subprocess.run(
            ["git", "branch", "--show-current"],
            capture_output=True,
            text=True,
            check=True
        ).stdout.strip()

    # --------------------------------------------------
    # GIT OPERATIONS
    # --------------------------------------------------

    def _stage_files(self, files):
        if not files:
            raise Exception("No Python files to stage")

        subprocess.run(["git", "add"] + files, check=True)

    # --------------------------------------------------

    def _commit(self, message):
        subprocess.run(
            ["git", "commit", "-m", message],
            check=True
        )

    # --------------------------------------------------
    # GITHUB API
    # --------------------------------------------------

    def _headers(self):
        return {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json"
        }

    # --------------------------------------------------

    def create_pr(self, title: str = "AI Generated PR") -> int:
        """
        Full automated flow:
        - detect files
        - ask commit message
        - commit
        - create PR
        """

        branch = self._get_current_branch()
        files = self._get_py_changes()

        if not files:
            raise Exception("No Python file changes detected")

        print("\n📄 Python files detected:")
        for f in files:
            print(f" - {f}")

        # --------------------------------------------------
        # USER INPUT (commit message)
        # --------------------------------------------------

        default_msg = f"AI update: {', '.join(files)}"

        commit_message = input(
            f"\n✏️ Enter commit message [{default_msg}]: "
        ) or default_msg

        # --------------------------------------------------
        # GIT FLOW
        # --------------------------------------------------

        print("\n📦 Staging files...")
        self._stage_files(files)

        print("💾 Creating commit...")
        self._commit(commit_message)

        # --------------------------------------------------
        # CREATE PR
        # --------------------------------------------------

        print("🔀 Creating PR...")

        url = f"{self.base_url}/repos/{self.repo}/pulls"

        payload = {
            "title": title,
            "head": branch,
            "base": self.base_branch,
            "body": self._build_body(files)
        }

        response = requests.post(url, headers=self._headers(), json=payload)

        if response.status_code not in [200, 201]:
            raise Exception(f"Error creating PR: {response.text}")

        pr_number = response.json()["number"]

        print(f"🚀 PR created: #{pr_number}")

        return pr_number

    # --------------------------------------------------

    def _build_body(self, files):
        body = "## AI Generated PR\n\n"
        body += "### Modified/New Python files:\n"

        for f in files:
            body += f"- `{f}`\n"

        body += "\n---\nGenerated by AI Code Review System"
        return body